# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

keccak256_string <- function(input) {
    .Call(`_keccak256r_keccak256_string`, input)
}

keccak256_raw <- function(input) {
    .Call(`_keccak256r_keccak256_raw`, input)
}

keccak256_file <- function(filepath) {
    .Call(`_keccak256r_keccak256_file`, filepath)
}

